version: '3.4'

x-common-env: &common-env
  SECRET_KEY: "liezie1ee3puHieh"
  SUBNET: "123.123.123.0/24"
  DOMAIN: "personalimuno.com"
  HOSTNAMES: "serunting.personalimuno.com"
  POSTMASTER: "admin"
  TLS_FLAVOR: "cert"
  AUTH_RATELIMIT_IP: "5/hour"
  AUTH_RATELIMIT_USER: "50/day"
  DISABLE_STATISTICS: "True"
  ADMIN: "true"
  INITIAL_ADMIN_ACCOUNT: "admin"
  INITIAL_ADMIN_DOMAIN: "personalimuno.com"
  INITIAL_ADMIN_PW: "PASSWORD"
  INITIAL_ADMIN_MODE: "ifmissing"
  SESSION_COOKIE_SECURE: "false"
  WEBMAIL: "roundcube"
  API: "false"
  WEBDAV: "radicale"
  ANTIVIRUS: "clamav"
  SCAN_MACROS: "true"
  MESSAGE_SIZE_LIMIT: "50000000"
  MESSAGE_RATELIMIT: "200/day"
  RELAYNETS: ""
  RELAYHOST: ""
  FETCHMAIL_ENABLED: "true"
  FETCHMAIL_DELAY: "600"
  RECIPIENT_DELIMITER: "+"
  DMARC_RUA: "admin"
  DMARC_RUF: "admin"
  WELCOME: "false"
  WELCOME_SUBJECT: "Welcome to your new email account"
  WELCOME_BODY: "Welcome to your new email account, if you can read this, then it is configured properly!"
  COMPRESSION: ""
  COMPRESSION_LEVEL: ""
  WEBROOT_REDIRECT: "/webmail"
  WEB_ADMIN: "/admin"
  WEB_WEBMAIL: "/webmail"
  WEB_API: "/api"
  SITENAME: "Personalimuno"
  WEBSITE: "https://www.personalimuno.com"
  COMPOSE_PROJECT_NAME: "mailu"
  CREDENTIAL_ROUNDS: "12"
  REAL_IP_HEADER: ""
  REAL_IP_FROM: ""
  REJECT_UNLISTED_RECIPIENT: ""
  LOG_LEVEL: "WARNING"
  TZ: "Asia/Jakarta"
  DEFAULT_SPAM_THRESHOLD: "50"
  API_TOKEN: ""
  LD_PRELOAD: "/usr/lib/libhardened_malloc.so"

services:

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/root/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 123.123.123.254

  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: always
    environment:
      <<: *common-env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "62.72.47.71:25:25"
      - "62.72.47.71:465:465"
      - "62.72.47.71:587:587"
      - "62.72.47.71:110:110"
      - "62.72.47.71:995:995"
      - "62.72.47.71:143:143"
      - "62.72.47.71:993:993"
    expose:
      - "80"
      - "443"
    networks:
      - default
      - webmail
      - radicale

    volumes:
      - "/root/mailu/certs:/certs"
      - "/root/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 123.123.123.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
    environment:
      <<: *common-env
    restart: always
    networks:
      default:
        ipv4_address: 123.123.123.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
    restart: always
    environment:
      <<: *common-env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/root/mailu/data:/data"
      - "/root/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 123.123.123.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: always
    environment:
      <<: *common-env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/root/mailu/mail:/mail"
      - "/root/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 123.123.123.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
    restart: always
    environment:
      <<: *common-env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/root/mailu/mailqueue:/queue"
      - "/root/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 123.123.123.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
    hostname: oletools
    restart: always
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 123.123.123.254

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
    hostname: antispam
    restart: always
    environment:
      <<: *common-env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - noinet
    volumes:
      - "/root/mailu/filter:/var/lib/rspamd"
      - "/root/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 123.123.123.254

  antivirus:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
    restart: always
    environment:
      <<: *common-env
    volumes:
      - "/root/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 123.123.123.254

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-2.0}
    restart: always
    volumes:
      - "/root/mailu/dav:/data"
    networks:
      - radicale

  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2.0}
    restart: always
    environment:
      <<: *common-env
    volumes:
      - "/root/mailu/data/fetchmail:/data"
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 123.123.123.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: always
    environment:
      <<: *common-env
    volumes:
      - "/root/mailu/webmail:/data"
      - "/root/mailu/overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 123.123.123.0/24
  radicale:
    driver: bridge
  webmail:
    driver: bridge
  noinet:
    driver: bridge
    internal: true
