version: '3.8'

services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    ports:
      - "58000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/yacht:/config
    restart: always
